apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile
spec:
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: az-secret
    shareName: aksshare
    readOnly: false