apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile
spec:
  storageClassName: azurefile-csi-premium
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: az-secret
    shareName: aksshare
    readOnly: false
  mountOptions:
    - actimeo=30
    - mfsymlinks